### ISSUE TITLE
📚 Documentation: Missing Screenshot 

### ISSUE THREAD

**Issue by scortier** [appwrite/builtwith#1]
### 💭 Description
There are 4 screenshot added in  [builtwith/docs](https://github.com/appwrite/builtwith/tree/main/docs) while in `README.md` 5 screenshot [links](https://github.com/appwrite/builtwith/blob/dce64f353e8239a3055bd47d27f5d86429bd0bb2/README.md?plain=1#L56) are mentioned. 

### Screenshot of Issue: 
<img width="441" alt="image" src="https://github.com/appwrite/builtwith/assets/44753901/2770687a-b86c-4093-9b95-ee4633f88426">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by scortier** [comment]
Hi @Meldiron,
Can you please help me in finding whether we need to remove 5th screenshot link or need to add screenshot pic in `buildwith/docs/` ?

**Comment by Meldiron** [comment]
We can remove 5th screenshot. Would you like to submit a PR? 😇

**Comment by scortier** [comment]
Sure!!

**Comment by scortier** [comment]
PR got merged, closing this issue!
