### ISSUE TITLE
🐛 Bug Report: GitHub login is not working

### ISSUE THREAD

**Issue by adityaoberai** [appwrite/builtwith#11]
### 👟 Reproduction steps

Go to the Built With Appwrite page and click on the GitHub login button

### 👍 Expected behavior

The user should login.

### 👎 Actual Behavior

The page just reloads, and sign in button shows no indication of a logged-in user.

https://www.loom.com/share/20d826a21f924e01868fca978c3da9b2

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by loks0n** [comment]
Fixed with #13
