### ISSUE TITLE
UI Improvement: Making Site Responsive

### ISSUE THREAD

**Issue by Isha988** [appwrite/builtwith#2]
#  📝 Description
Although the UI of the site is alright yet there is a need to make it responsive as it is not looking good on small screens.

# 🖼️ Screenshots 
![IMG_20230514_174351](https://github.com/appwrite/.github/assets/89572340/70ecae9d-91e8-464e-9331-41ed8c0cc197)
![IMG_20230514_174336](https://github.com/appwrite/.github/assets/89572340/e56f48ca-3c0d-4023-9568-bb6ba64c327b)

# 👀 Have you spent some time checking if this issue has been raised before?
I checked and didn't find a similar issue

# Are you working on it?
I would love to work on this issue and want to make further discussions and suggestions for UI updates.

**Comment by christyjacob4** [comment]
Hey @Isha988 Thanks for your interest in the design of the website. 

Can you share more about the proposed changes before we start working on it?

**Comment by Isha988** [comment]
Hey @christyjacob4, these are some of the changes that we should have in BuiltWith website
# Image 1
![Screenshot 2023-05-16 at 20-41-15 Built with Appwrite](https://github.com/appwrite/builtwith/assets/89572340/0110b5d7-855c-4a64-a9cf-322673299712)
# Image 2
![Screenshot 2023-05-16 at 20-42-18 Built with Appwrite](https://github.com/appwrite/builtwith/assets/89572340/63b1e213-2ecd-4585-b706-426a9fc39fe1)

# Cause of problem
Although the most of the code is written perfectly except some of the part and have all the necessary classes yet **classes for mobile screen are not working as expected**.

**Comment by loks0n** [comment]
Thanks for bringing this up @Isha988 🙏 

Seems like the issue here has been solved by adding the `viewport` meta tag, so I'm going to close this issue.
